### ISSUE TITLE
Option to disaggregate deaths from incidence counts

### ISSUE THREAD

**Issue by fintzij** [klumbard/covidWeekly#2]
Incident deaths are currently included in the counts of positive tests (https://covidtracking.com/about-data/faq), i.e., num. positive = incidence + deaths. We should add an option to subtract weekly deaths from weekly positives so that num. positive can be interpreted as incidence.

**Comment by klumbard** [comment]
I've been thinking about this and not sure I agree with it. The FAQ says "We also include data on deaths, but you can assume that these numbers are also incorporated into the positive case count." I assume that this means the deaths are incorporated into the **cumulative** positive count, not the **incidence** data. 

You say we should "add an option to subtract weekly deaths from weekly positives", but to me it's not obvious that a death showing up in the death incidence column corresponds to incidence of a  positive test in the same aggregation interval.

Example:

- Person A tests positive on 2020-03-01

- We aggregate from 2020-03-01 to 2020-03-07

- Person A dies on 2020-03-10 and shows up in the death incidence column for that day

- We subtract their death from the positive column, but this is the positive column for the **next week** which starts on 2020-03-08, NOT the week Person A's positive count actually came from

Since we have no way of connecting the date of positive test with the date of death for any individual in the dataset, there's no guarantee that you're de-incrementing the positive column in the correct time interval. The example above is for weekly intervals, but we are working towards allowing arbitrary aggregation intervals. If the interval is 2 days instead of one week, the issue in the above example will be amplified.

**Comment by fintzij** [comment]
I've been thinking about this and was actually all set to agree with you, but I think you laid out the exact reason why we should be subtracting deaths off from incidence :-D 

Let's forget about aggregation for a second, because this actually applies when we don't aggregate up as well. The issue, as you pointed out in the last bullet, is that we have individuals contributing to the incidence count at times when they were not actually incident cases. I think that our goal should be to get as close as possible to being able to interpret incidence counts as counts of incident cases, not incident cases + incident deaths. 

How about first subtracting incident deaths from incident cases, and then aggregating? I think this would solve the issue, no?

**Comment by klumbard** [comment]
Our current thinking is that this isn't actually an issue in the raw data, so we can keep it in the back of our minds if something brings it back up, but I'm closing the issue for now.
