### ISSUE TITLE
Bug in aggregation

### ISSUE THREAD

**Issue by fintzij** [klumbard/covidWeekly#5]
I am running into an issue where it is possible to have more positives than tests. Code to reproduce the error below: 

```
# pull the data
agg_interval = 3 # three day aggregation
states_ab = c(state.abb, "DC", "PR")
states_full = c(state.name, "District of Columbia", "Puerto Rico")
dat = get_state_dat(agg_interval = agg_interval, t0 = "2020-03-15")

# sort dat so it's in the same order as states_ab
dat = dat[order(match(dat$state, states_ab)),]
dat$state = factor(dat$state, levels = states_ab)

# grab the numbers of tests and positives
p = vector("list", 52); r = vector("list", 52)
for(k in 1:52) {
   p[[k]] = with(subset(dat, t0 == 0 & state == states_ab[k]), pos)
   r[[k]] = with(subset(dat, t0 == 0 & state == states[k]), tests)
}

p[[8]] / r[[8]] # something wrong with Delaware 
```

**Comment by klumbard** [comment]
![image](https://user-images.githubusercontent.com/28765127/79984298-f6369100-8476-11ea-97a3-b27c51fb889c.png)


This isn't an issue with the aggregation code, but the raw data. See attached image - you can see that the (cumulative) number of negatives in Delaware went from 10415 on 4/10 to 9624 on 4/11. So the corresponding negative incidence column has a negative value. The total is then defined by adding positive incidence and negative incidence together, and thus also ends up negative on 4/11.

Not sure how to deal with this issue in general. Actually, the same thing happened in Alaska on 4/13, and someone opened a github issue with them on their repo: https://github.com/COVID19Tracking/issues/issues/221. It hasn't been responded to and the issue remains in the data 😢. 

In this case you don't see that there's an issue with Alaska, because the aggregation of incidence on other days is enough to overcome the negative valued incidence on one day, so the aggregated # of positives is still less than the aggregated # of tests. In Delaware's case, the discrepancy was strong enough that the aggregated total # of tests in the 3-day window, after aggregation, was smaller than the number of positive tests after aggregation.
